In [2]:
%cd ..

d:\HUST\20232\ML\Project_OCR\HandwritingRecognition


In [6]:
import os
import torch
from utils.StrLabelConverter import StrLabelConverter

In [15]:
alphabet = open(os.path.join('data/mychar.txt')).read()
convert = StrLabelConverter(alphabet)

In [16]:
len(alphabet)

158

In [18]:
convert.numClass

159

In [10]:
enc = convert.encode(['12345', '012345'])
enc

(tensor([13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17], dtype=torch.int32),
 tensor([5, 6], dtype=torch.int32))

In [12]:
convert.decode(enc[0], enc[1])

['12345', '012345']

: 

In [4]:
from dataset import *

In [5]:
dataset = DatasetImg('data/img', 'data/label', 512, 32)

In [6]:
dataloader = torch.utils.data.DataLoader(
            dataset,
            batch_size=64,
            shuffle=True)

In [7]:
img, label = next(iter(dataloader))

In [22]:
alphabet = open(os.path.join('data/char.txt')).read().rstrip()

converter = strLabelConverter(alphabet, ignore_case=True)
numClass = converter.numClass
numClass



145

In [20]:
converter.encode(label)

(tensor([45, 28,  1,  ..., 41, 47, 11], dtype=torch.int32),
 tensor([91, 76, 94, 78, 78, 88, 64, 60, 20, 79, 33, 62, 68, 59, 95,  9, 70, 82,
         68, 54, 41, 48, 28, 92, 53, 90, 71, 42, 71, 73, 70, 53, 73, 63, 68, 74,
         78, 62, 54, 81, 81, 74, 77, 87, 72, 58, 26, 80, 41, 69, 68, 78, 81, 65,
         69, 80, 82, 72, 70, 89, 70, 84, 68, 69], dtype=torch.int32))

In [27]:
input = torch.rand(145, 64, 128)
input_lengths = torch.full(size=(64,), fill_value=128, dtype=torch.long)
target, target_lengths = converter.encode(label)

criterion = torch.nn.CTCLoss()
loss = criterion(input.log_softmax(2), target, input_lengths, target_lengths)
loss

tensor(9.1000)

In [28]:
input.log_softmax(2)

tensor([[[-5.2475, -4.9321, -4.9033,  ..., -5.0675, -5.3034, -4.9360],
         [-4.6650, -4.6435, -4.8410,  ..., -4.8973, -4.5423, -5.0474],
         [-4.5012, -4.5204, -5.0546,  ..., -5.1592, -4.7797, -5.1051],
         ...,
         [-4.5140, -5.3827, -4.7316,  ..., -5.3433, -4.4627, -5.3066],
         [-5.0414, -4.6611, -5.1869,  ..., -5.1915, -4.6133, -4.5173],
         [-4.7702, -4.9313, -5.0115,  ..., -4.8028, -5.1198, -4.5164]],

        [[-4.7842, -4.7029, -4.8137,  ..., -4.4406, -4.4129, -5.3209],
         [-5.0668, -4.4643, -4.8460,  ..., -5.0854, -5.4086, -4.8029],
         [-5.3918, -4.6643, -4.6111,  ..., -4.8371, -4.6395, -4.4314],
         ...,
         [-4.6398, -4.9631, -4.7801,  ..., -5.3325, -5.1018, -4.8854],
         [-5.1790, -4.8521, -4.4995,  ..., -5.3118, -5.3429, -4.4443],
         [-5.2877, -4.5953, -4.6646,  ..., -5.0649, -4.7818, -5.3007]],

        [[-4.8452, -5.0485, -5.1594,  ..., -4.7784, -4.4441, -4.6611],
         [-4.6180, -5.2239, -4.6367,  ..., -4